version: '2'
services:
    sioe_dev-app:
        image: sioe_dev
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sioe_dev-mysql:3306/sioe_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sioe_dev-mysql:
        extends:
            file: mysql.yml
            service: sioe_dev-mysql
